
scss_files: "./src/**/*.scss"
exclude: './src/styles/base/normalize.scss'

# Default severity of all linters.
linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  Comment:
    enabled: false

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4

  LeadingZero:
    enabled: false

  MergeableSelector:
    enabled: true
    force_nesting: false

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: camel_case # or 'camel_case', or 'snake_case', or a regex pattern

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
excluded_identifiers: ['placeholder']
